version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-demo
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  sender:
    build: .
    container_name: rabbitmq-sender
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - env.docker
    command: ["npm", "run", "start:sender"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "node.*sender.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  listener:
    build: .
    container_name: rabbitmq-listener
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - env.docker
    command: ["npm", "run", "start:listener"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "node.*listener.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  rabbitmq_data: 